### ISSUE TITLE
fix: MkUser() prompt overhaul

### ISSUE THREAD

**Issue by randomthingsandstuff** [gottaeat/cloudvirt#4]
- [x] Get rid of extra newline when you're prompted for data
- [x] Make the SSH key stuff "done" when it gets a blank line instead of using "done" sentinel.
- [x] Allow blank password to mean "don't set a password, don't allow password login for this user" (if its not too hard to sort out)

**Comment by gottaeat** [comment]
> Get rid of extra newline when you're prompted for data￼

this is due to us still using the logger to print the prompts, either i hook up a different handler with the `handler.terminator` set to `""` or we print w/o the logger.

**Comment by gottaeat** [comment]
> Allow blank password to mean "don't set a password, don't allow password login for this user" (if its not too hard to sort out)

currently we force `lock_passwd` on every user in the produced `user-data`, and also force a passwd to be provided.
